### ISSUE TITLE
Solutions are not computed lazily

### ISSUE THREAD

**Issue by mitchellwrosen** [LeventErkok/linearEqSolver#2]
Hello Levent! 

I may be misunderstanding something, but when I run this example code from the documentation:

```haskell
>>> take 3 `fmap` solveRationalLinearEqsAll Z3 [[2.4, 3.6]] [12]
[[0 % 1,10 % 3],[(-3) % 2,13 % 3],[(-3) % 4,23 % 6]]
```

I see no results (in both interpreted and compiled code). Any idea what the problem might be? Thanks!

**Comment by LeventErkok** [comment]
Ah, quite right. This broke with SBV 7.0:

   https://github.com/LeventErkok/sbv/blob/master/CHANGES.md#version-70-2017-07-19

In SBV >= 7.0, the `allSat` function is no longer lazy; which the `linearEqSolver` was counting on. Instead, it takes an optional argument that says how many models we want at the most.

We need to change `solveRationalLinearEqsAll` to also take a similar argument and fix the documentation.

If you want to keep the old behavior, you'll have to downgrade the SBV dependency to say < 7.0, I'm afraid.

**Comment by LeventErkok** [comment]
@mitchellwrosen Fixed in https://github.com/LeventErkok/linearEqSolver/commit/a273edf75a06fe2ce96c9b52a5de2d71017cac7d

Will release a new version on hackage soon.

**Comment by LeventErkok** [comment]
Version #2 is now on hackage: http://hackage.haskell.org/package/linearEqSolver-2.0

Thanks for reporting.
