### ISSUE TITLE
Cabal install of v2.0 fails

### ISSUE THREAD

**Issue by mckibbenc** [LeventErkok/linearEqSolver#3]
When installing v2.0 of linearEqSolver from Cabal, the build fails with the following error:

`Math/LinearEquationSolver.hs:143:29: error:
    Not in scope: type constructor or class ‘SymWord’
    Perhaps you meant ‘SWord’ (imported from Data.SBV)
    |
143 | buildConstraints :: (Num a, SymWord a) => String -> [[a]] -> [a] -> Symbolic SBool
    |    `

**Comment by LeventErkok** [comment]
Thanks for the report. A new version is now on Hackage, which should address the problem: https://hackage.haskell.org/package/linearEqSolver-2.3

**Comment by mckibbenc** [comment]
Many thanks!  It now successfully installs from Cabal.
