### ISSUE TITLE
Exception when using Z3

### ISSUE THREAD

**Issue by mckibbenc** [LeventErkok/linearEqSolver#4]
I get the following error when trying to solve a system of equations using Z3 and linearEqSolver v2.3:

GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Prelude> import Math.LinearEquationSolver
Prelude Math.LinearEquationSolver> solveIntegerLinearEqs Z3 [[1,-1],[3,-2]] [0,-1]
*** Exception: Unable to locate executable for Z3
Executable specified: "z3"

CallStack (from HasCallStack):
  error, called at ./Data/SBV/SMT/SMT.hs:573:23 in sbv-8.6-4QEWrfdds2bERRyL3UyeG:Data.SBV.SMT.SMT

**Comment by LeventErkok** [comment]
You need to install the z3 SMT solver, making sure the `z3` executable is in your path. You can get a copy from here: https://github.com/Z3Prover/z3/releases/tag/z3-4.8.8
